### PR TITLE
Removed Redis dependency and require SecureRandom module

### PR DESCRIPTION
**Pull request by vpuzzella**

### CODE REVIEW

**Comment by zackkitzmiller** [comment]
Interesting, I wonder what's breaking 1.9.x here.

**Comment by vpuzzella** [comment]
@zackkitzmiller, I'm stumped. I ran the specs locally with Ruby 1.9.3-p551 and they passed.

**Comment by vpuzzella** [comment]
```
[vagrant@vagrant sixpack-rb]$ git status
On branch fix_dependencies
Your branch is up-to-date with 'origin/fix_dependencies'.
nothing to commit, working directory clean
[vagrant@vagrant sixpack-rb]$ ruby -v
ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-linux]
[vagrant@vagrant sixpack-rb]$ gem list bundler

*** LOCAL GEMS ***

bundler (1.7.6)
bundler-unload (1.0.2)
rubygems-bundler (1.4.4)
[vagrant@vagrant sixpack-rb]$ rspec
.............

Finished in 4.12 seconds (files took 0.1493 seconds to load)
13 examples, 0 failures
```

**Comment by vpuzzella** [comment]
Interesting. 1.9.3 build breaks after upgrading RubyGems to 2.5.1. This may also be a problem on the master branch because the last good build there used Ruby Gems 2.4.5.

**Comment by vpuzzella** [comment]
Confirmed. 1.9.3 build passes with RubyGems 2.4.5, but not 2.5.1:
```
[ sixpack-rb ](fix_dependencies)$ ruby -v
ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-darwin14.5.0]
[ sixpack-rb ](fix_dependencies)$ gem --version
2.4.5
[ sixpack-rb ](fix_dependencies)$ bundle install --jobs=3 --retry=3
Resolving dependencies...
Using rake 10.4.2
Using addressable 2.4.0
Using diff-lcs 1.2.5
Using json 1.8.3
Using rspec-support 3.3.0
Using bundler 1.7.6
Using rspec-core 3.3.2
Using rspec-expectations 3.3.1
Using rspec-mocks 3.3.2
Using rspec 3.3.0
Using sixpack-client 1.1.0 from source at .
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
[ sixpack-rb ](fix_dependencies)$ rspec
.............

Finished in 4.03 seconds (files took 0.20293 seconds to load)
13 examples, 0 failures
```

**Comment by vpuzzella** [comment]
bump?

**Comment by josegonzalez** [comment]
@vpuzzella can you try every point release between 2.4.8 and 2.5.1 to see where this breaks? Afaik we aren't doing anything weird here, so it might be a rubygems bug that we should report...

**Comment by vpuzzella** [comment]
@josegonzalez, 1.9.3 build with fails RubyGems >= 2.5.0.

RubyGems 2.4.5 passed: https://travis-ci.org/seatgeek/sixpack-rb/builds/108441015
RubyGems 2.4.6 passed: https://travis-ci.org/seatgeek/sixpack-rb/builds/108441469
RubyGems 2.4.7 passed: https://travis-ci.org/seatgeek/sixpack-rb/builds/108441765
RubyGems 2.4.8 passed: https://travis-ci.org/seatgeek/sixpack-rb/builds/108442384
RubyGems 2.5.0 failed: https://travis-ci.org/seatgeek/sixpack-rb/builds/108443031
RubyGems 2.5.1 failed: https://travis-ci.org/seatgeek/sixpack-rb/builds/108443265
RubyGems 2.5.2 failed: https://travis-ci.org/seatgeek/sixpack-rb/builds/108443519

**Comment by vpuzzella** [comment]
@josegonzalez, curious why you still support 1.9.3. It's been dead so-to-speak for almost a year: https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/

**Comment by josegonzalez** [comment]
We use ruby 1.9.3 in production. Don't ask, I'm embarrassed about it :(

**Comment by vpuzzella** [comment]
That's what I figured. Believe me, I know your pain. :(

**Comment by vpuzzella** [comment]
@josegonzalez , Build passes with RubyGems 2.5.2 and Bundler 1.11.2

**Pull request closed without merging**
