### PR TITLE
Better argument error message

### PR DESCRIPTION
**Pull request by Valve**

### CODE REVIEW

**Comment by zackkitzmiller** [comment]
I'm working on getting these tests fixed. I'll merge this when they pass.

**Comment by zackkitzmiller** [comment]
Could you merge in master when you have time?

**Comment by Valve** [comment]
You mean in master of my fork?

**Comment by zackkitzmiller** [comment]
Of this one, sorry. I just updated `seatgeek/sixpack-rb` to fix the broken tests.

**Pull request merged**
