### PR TITLE
Implement KPI setting on conversion

### PR DESCRIPTION
**Pull request by Valve**

### CODE REVIEW

**Comment by zackkitzmiller** [comment]
:+1:

**Comment by zackkitzmiller** [comment]
I'll tag a release today

**Comment by Valve** [comment]
@zackkitzmiller, btw, when I try to set a KPI on a participation call, it takes no effect. It only works on conversion. Is it by design?

**Comment by zackkitzmiller** [comment]
Yes. You cannot assign a KPI to a participation.

**Comment by Valve** [comment]
OK, here is a scenario:

We need to track AB conversions separately for logged-in vs anonymous users.
A logged in user makes a participation and then a conversion.
Then 9 anonymous users make a participation and then a conversion.

I tag logged in users with 'loggedin' KPI, and anonymous users with 'anonymous' KPI.
In the end I expect the numbers on the dashboard to be:

1/1 for logged in KPI
9/9 for anonymous KPI, 

but in reality they're:

1/10 for logged in KPI
9/10 for anonymous KPI, i.e. they don't convey the picture at all.

Please let me know if I"m misusing it and if it's possible to achieve this w/out setting up two experiments for anonymous/logged-in users.

**Comment by Valve** [comment]
I'll ask it on the project repo itself, I think it'll be more appropriate there.

**Pull request merged**
