### PR TITLE
Configurable

### PR DESCRIPTION
**Pull request by Valve**

### CODE REVIEW

**Comment by Valve** [comment]
oops, let me pull the latest

**Comment by zackkitzmiller** [comment]
We should keep the `host` param called host. This avoids breaking backwards compatibility, and keeps the language in the clients consistent.

**Comment by Valve** [comment]
I think it was 'host' only in the readme and base_url elsewhere so I just updated readme to reflect actual code

**Comment by zackkitzmiller** [comment]
Oh, you're definitely right on that, aren't you. I'm going to check the other clients to see if there's a pattern of that.

**Comment by Valve** [comment]
Please let me know if I should make it a 'host' option in the ruby library

**Comment by Valve** [comment]
@zackkitzmiller, please let me know if there is a chance you'll merge this PR

**Comment by zackkitzmiller** [comment]
Yup! This will get merged. I'm out of the office this week, so probably Monday.

**Comment by zackkitzmiller** [comment]
@Valve I can't merge this in, can you update w/ the main fork?

**Comment by Valve** [comment]
I've created a new PR for this, closing current

**Pull request closed without merging**
