### PR TITLE
Removed Redis dependency and require SecureRandom module

### PR DESCRIPTION
**Pull request by vpuzzella**
Redis is not required and specs would not run because SecureRandom was not defined

### CODE REVIEW

**Comment by vpuzzella** [comment]
Ruby 1.9.3 build is failing. Not sure w.

**Comment by zackkitzmiller** [comment]
There is a lot of refactoring in here that seems unrelated to Redis or securerandom. I'l like to see those each as separate PRs, and then a possible third for the refactoring. In addition this breaks on Ruby 1.9.x, making this PR unmergable.

**Comment by vpuzzella** [comment]
My mistake. I'll close this and create separate PRs when I figure out the 1.9.3 issue.

**Comment by zackkitzmiller** [comment]
Sounds good to me! Thanks for the contribution.

**Pull request closed without merging**
